apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: banking-operations-monitor
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ${DOCKERHUB_USERNAME}/banking_operations_monitor:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: banking-operations-monitor-config
              key: DJANGO_SETTINGS_MODULE
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              name: banking-operations-monitor-config
              key: DJANGO_DEBUG
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: banking-operations-monitor-secrets
              key: DJANGO_SECRET_KEY
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: banking-operations-monitor-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: banking-operations-monitor-config
              key: MONGODB_PORT
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: banking-operations-monitor-config
              key: MONGODB_DATABASE
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: banking-operations-monitor-secrets
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banking-operations-monitor-secrets
              key: MONGODB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: banking-operations-monitor
spec:
  selector:
    app: django
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer