name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
      - name: Add safe directory
        run: git config --global --add safe.directory C:/actions-runner/_work/valuable_gathering_platform/valuable_gathering_platform
      
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment for running tests
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: $env:RUN_LIVE_DB_TESTS=1; python manage.py test

      - name: Build Docker image
        shell: powershell
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering
        run: |
          docker build -t $env:DOCKER_IMAGE .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        shell: pwsh
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering
        run: |
          docker push $env:DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    steps:
      - name: Deploy container directly
        shell: pwsh
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering
        run: |
          Write-Output "Pulling Docker image..."
          docker pull $env:DOCKER_IMAGE
          
          Write-Output "Stopping and removing any existing container..."
          docker stop valuable_gathering || Write-Output "No container to stop."
          docker rm valuable_gathering || Write-Output "No container to remove."
          
          Write-Output "Starting new container..."
          docker run -d --name valuable_gathering -p 8000:8000 $env:DOCKER_IMAGE
          
          Write-Output "Fetching container logs (first 20 lines):"
          docker logs valuable_gathering --tail 20