name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:

      - name: Add safe directory
        run: git config --global --add safe.directory C:/actions-runner/_work/valuable_gathering_platform/valuable_gathering_platform
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: powershell -ExecutionPolicy Bypass -Command "docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering ."
      

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    steps:
      - name: Deploy with PowerShell's SSH
        run: |
          ssh -i $env:WINDOWS_SSH_KEY $env:WINDOWS_USER@${{ secrets.WINDOWS_HOST }} "docker pull $env:DOCKER_IMAGE && docker stop valuable_gathering || true && docker rm valuable_gathering || true && docker run -d --name valuable_gathering -p 8000:8000 $env:DOCKER_IMAGE"
        shell: pwsh
        env:
          WINDOWS_SSH_KEY: ${{ secrets.WINDOWS_SSH_KEY }}
          WINDOWS_USER: ${{ secrets.WINDOWS_USER }}
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/valuable_gathering
