global:
  scrape_interval: 15s     # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s      # How long until a scrape times out

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []      # Alertmanager targets (can be added later)

# Rule files specify alerting rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node exporter for host system metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    
  # Django application metrics
  - job_name: "banking_it_ops"
    metrics_path: /metrics
    static_configs:
      - targets: ["django:8000"]
    
  # Custom resource metrics from text files
  - job_name: "banking_resource_metrics"
    file_sd_configs:
      - files:
          - /prometheus_metrics/*.prom
        refresh_interval: 1m

  # MongoDB metrics
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  # Docker metrics
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d  # Data retention period (15 days)
      size: 5GB  # Maximum storage size

# Web interface configuration
web:
  listen_address: 0.0.0.0:9090
  external_url: http://localhost:9090  # Adjust for production
  page_title: Banking IT Operations Metrics

